# fly.toml app configuration file generated for rama-echo on 2024-03-19T23:16:07+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rama-echo'
primary_region = 'lhr'

[experimental]
cmd = [
    './rama',
    'echo',
    '-i',
    '0.0.0.0',
    '-p',
    '8080',
    '-c',
    '2048',
    '-t',
    '16',
]

[build]
image = 'glendc/rama:latest'

[metrics]
port = 9091
path = "/metrics"

[[services]]
protocol = 'tcp'
internal_port = 8080
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[[services.ports]]
handlers = ["proxy_proto"]
port = 80

[[services]]
protocol = 'tcp'
internal_port = 8443
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[[services.ports]]
handlers = ["proxy_proto"]
port = 443

[[vm]]
memory = '256mb'
cpu_kind = 'shared'
cpus = 1
