[package]
categories = ["asynchronous", "network-programming"]
edition = "2021"
name = "rama"
version = "0.1.0"
description = "proxy framework using Tokio written purely in Rust"
homepage = "https://github.com/plabayo/llama"
readme = "README.md"
keywords = ["io", "async", "non-blocking", "futures"]
license = "MIT"
repository = "https://github.com/plabayo/llama"

[dependencies]
anyhow = "1.0.70"
futures = "0.3.28"
pin-project = "1.0.12"
pin-project-lite = "0.2.9"
thiserror = "1.0.40"
tokio = { version = "1", features = ["full"] }
tower-service = "0.3.2"
tracing = "0.1.37"
