[workspace]
members = [".", "rama-cli"]

[workspace.package]
version = "0.2.0"
license = "MIT OR Apache-2.0"
edition = "2021"
repository = "https://github.com/plabayo/rama"
homepage = "https://ramaproxy.org"
keywords = ["io", "async", "non-blocking", "futures"]
categories = ["asynchronous", "network-programming"]
authors = ["Glen De Cauwsemaecker <glen@plabayo.tech>"]
rust-version = "1.75.0"

[package]
name = "rama"
readme = "README.md"
documentation = "https://docs.rs/rama"
description = "modular proxy framework"
version = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }
authors = { workspace = true }
rust-version = { workspace = true }

[features]
default = []
full = ["compression"]
compression = ["dep:async-compression"]

[build-dependencies]
rustversion = "1.0.9"

[dependencies]
async-compression = { version = "0.4", optional = true, features = ["tokio"] }
bytes = "1"
futures = "0.3.29"
futures-core = "0.3"
futures-util = { version = "0.3", default-features = false, features = ["alloc"] }
h2 = "0.4"
headers = "0.4"
http = "1"
http-body = "1"
http-body-util = "0.1"
httparse = "1.8"
hyper = { package = "rama-hyper", version = "0.1001000", features = ["http1", "http2", "server"] }
hyper-util = { package = "rama-hyper-util", version = "0.1002", features = ["tokio", "server-auto"] }
matchit = "0.7.3"
mime = "0.3.17"
pin-project-lite = "0.2.13"
pki-types = { package = "rustls-pki-types", version = "^1" }
rcgen = "0.12.0"
rustls = "0.22"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_urlencoded = "0.7"
sync_wrapper = "0.1.2"
tokio = { version = "1", features = ["macros"] }
tokio-graceful = "0.1"
tokio-rustls = "0.25"
tokio-util = "0.7"
tracing = { version = "0.1" }
uuid = { version = "1.6", features = ["v4"] }

[dev-dependencies]
rustversion = "1.0.9"
tokio = { version = "1", features = ["full"] }
tokio-test = { version = "0.4.3" }
tracing = "0.1"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
