[package]
categories = ["asynchronous", "network-programming"]
edition = "2021"
name = "rama"
version = "0.1.0"
description = "proxy framework using Tokio written purely in Rust"
homepage = "https://github.com/plabayo/llama"
readme = "README.md"
keywords = ["io", "async", "non-blocking", "futures"]
license = "BSL"
repository = "https://github.com/plabayo/llama"

[[bin]]
name = "rama"
path = "./src/bin/rama/main.rs"

[dependencies]
anyhow = "1"
pin-project-lite = "0.2"
thiserror = "1"
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7"
tower = { version = "0.4" }
tracing = "0.1"

[dev-dependencies]
tower = { version = "0.4", features = ["limit"] }
tracing-subscriber = "0.3.16"
