[package]
categories = ["asynchronous", "network-programming"]
edition = "2021"
name = "rama"
version = "0.2.0"
description = "proxy framework using Tokio written purely in Rust"
homepage = "https://github.com/plabayo/llama"
readme = "README.md"
keywords = ["io", "async", "non-blocking", "futures"]
license = "BSL"
repository = "https://github.com/plabayo/llama"
# [[bin]]
# name = "rama"
# path = "./src/bin/rama/main.rs"

[dependencies]
bytes = "1.4"
pin-project-lite = "0.2"
tokio = { version = "1", features = ["full"] }
tokio-util = "^0.7.8"
tower-async = { version = "0.1" }

[dev-dependencies]
tokio-test = "0.4"
tower = { version = "0.4", features = ["limit", "util"] }
tracing-subscriber = "0.3"
