[package]
categories = ["asynchronous", "network-programming"]
edition = "2021"
name = "rama"
version = "0.1.0"
description = "proxy framework using Tokio written purely in Rust"
homepage = "https://github.com/plabayo/llama"
readme = "README.md"
keywords = ["io", "async", "non-blocking", "futures"]
license = "MIT"
repository = "https://github.com/plabayo/llama"

[dependencies]
tokio = { version = "1", features = ["full"] }
