[workspace]
members = [".", "rama-cli"]

[workspace.package]
version = "0.2.0"
license = "MIT OR Apache-2.0"
edition = "2021"
repository = "https://github.com/plabayo/rama"
homepage = "https://ramaproxy.org"
keywords = ["io", "async", "non-blocking", "futures"]
categories = ["asynchronous", "network-programming"]
authors = ["Glen De Cauwsemaecker <glen@plabayo.tech>"]

[package]
name = "rama"
readme = "README.md"
documentation = "https://docs.rs/rama"
description = "distortion proxy framework"
version = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }
authors = { workspace = true }

[features]
default = ["tracing"]
tracing = ["dep:tracing"]

[build-dependencies]
rustversion = "1.0.9"

[dependencies]
bytes = "1"
futures = "0.3.29"
futures-util = { version = "0.3", default-features = false, features = ["alloc"] }
headers = "0.4"
http = "1"
http-body = "1"
http-body-util = "0.1"
httparse = "1.8"
hyper = { package = "rama-hyper", version = "0.1001000", features = ["http1", "http2", "server"] }
hyper-util = { package = "rama-hyper-util", version = "0.1002", features = ["server-auto"] }
matchit = "0.7.3"
pin-project-lite = "0.2.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_urlencoded = "0.7"
sync_wrapper = "0.1.2"
tower = { version = "0.4.13", default-features = false, features = ["util", "make"] }
tower-layer = "0.3.2"
tower-service = "0.3.2"
tracing = { version = "0.1", optional = true }

[dev-dependencies]
pki-types = { package = "rustls-pki-types", version = "^1" }
rcgen = "0.12.0"
rustversion = "1.0.9"
tracing = "0.1"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dev-dependencies.tower]
package = "tower"
version = "0.4.13"
features = [
    "util",
    "timeout",
    "limit",
    "load-shed",
    "steer",
    "filter",
]
