[advisories]
version = 2
ignore = [
    # can be removed once aws-ls-rc moved away from paste as well:
    # <https://github.com/aws/aws-lc-rs/issues/722>
    "RUSTSEC-2024-0436",
]

[licenses]
confidence-threshold = 0.93
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "MIT",
    "MPL-2.0",
    "BSD-3-Clause",
    "ISC",
    "Unicode-3.0",
    "OpenSSL",
    "Zlib",
]

[bans]
multiple-versions = "warn"
highlight = "all"
skip-tree = []

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-git = []
