[book]
authors = ["Glen De Cauwsemaecker <glen@plabayo.tech>"]
language = "en"
multilingual = false
src = "src"
title = "Rama"

[output.html]
git-repository-url = "https://github.com/plabayo/rama"

[preprocessor.graphviz]
command = "mdbook-graphviz"
output-to-file = false
