[book]
authors = ["Glen De Cauwsemaecker <glen@plabayo.tech>"]
language = "en"
multilingual = false
src = "src"
title = "Rama"

[output.html]
git-repository-url = "https://github.com/plabayo/rama"
edit-url-template = "https://github.com/plabayo/rama/edit/main/docs/book/{path}"
additional-css = ["custom.css"]
site-url = "/book/"
cname = "ramaproxy.org"

[output.html.print]
enable = false

# [preprocessor.graphviz]
# command = "mdbook-graphviz"
# output-to-file = false
