[package]
name = "rama-http"
description = "rama http layers, services and other utilities"
version = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }
authors = { workspace = true }
rust-version = { workspace = true }

[features]
default = []
compression = ["dep:async-compression"]
telemetry = ["rama-core/telemetry"]
tls = ["dep:rama-tls"]

[dependencies]
async-compression = { workspace = true, features = [
    "tokio",
    "brotli",
    "zlib",
    "gzip",
    "zstd",
], optional = true }
bytes = { workspace = true }
const_format = { workspace = true }
futures-core = { workspace = true }
futures-lite = { workspace = true }
headers = { workspace = true }
http = { workspace = true }
http-body = { workspace = true }
http-body-util = { workspace = true }
mime = { workspace = true }
mime_guess = { workspace = true }
paste = { workspace = true }
pin-project-lite = { workspace = true }
rama-utils = { version = "0.2.0-alpha.2", path = "../rama-utils" }
rama-core = { version = "0.2.0-alpha.2", path = "../rama-core", features = ["http"] }
rama-ua = { version = "0.2.0-alpha.2", path = "../rama-ua" }
rama-http-types = { version = "0.2.0-alpha.2", path = "../rama-http-types" }
rama-net = { version = "0.2.0-alpha.2", path = "../rama-net", features = ["http"] }
rama-tls = { version = "0.2.0-alpha.2", path = "../rama-tls", optional = true }
serde = { workspace = true, features = ["derive"] }
serde_html_form = { workspace = true }
serde_json = { workspace = true }
sync_wrapper = { workspace = true }
tracing = { workspace = true }
regex = { workspace = true }
base64 = { workspace = true }
httpdate = { workspace = true }
tokio = { workspace = true, features = ["macros", "fs", "io-std"] }
http-range-header = { workspace = true }
iri-string = { workspace = true }
tokio-util = { workspace = true, features = ["io"] }
uuid = { workspace = true, features = ["v4"] }
percent-encoding = { workspace = true }
bitflags = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
tokio-test = { workspace = true }

[package.metadata.cargo-public-api-crates]
allowed = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
