[package]
categories = ["asynchronous", "network-programming"]
edition = "2021"
name = "rama"
version = "0.2.0"
description = "proxy framework using Tokio written purely in Rust"
homepage = "https://github.com/plabayo/rama"
readme = "../README.md"
keywords = ["io", "async", "non-blocking", "futures"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/plabayo/rama"

[dependencies]
http = "0.2.9"
matchit = "0.7.3"
pin-project-lite = "0.2.13"
tokio = { version = "1.33.0", features = ["net", "io-util"] }
tokio-graceful = "0.1.5"
tower-async = { version = "0.1.1", features = ["util", "timeout", "filter", "limit"] }
tracing = "0.1.40"

[dev-dependencies]
futures = "0.3.29"
tokio = { version = "1.33.0", features = ["full"] }
tokio-test = "0.4.3"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
