[package]
name = "rama-net"
description = "rama network types and utilities"
version = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }
authors = { workspace = true }
rust-version = { workspace = true }

[features]
default = []
full = ["http", "rustls", "boring", "telemetry"]
http = ["dep:rama-http-types", "rama-core/http"]
tls = ["dep:hex"]
rustls = ["tls", "dep:rustls"]
boring = ["tls", "dep:boring", "dep:nom"]
rustls-ring = ["rustls", "rustls/ring"]
telemetry = ["rama-core/telemetry"]

[dependencies]
base64 = { workspace = true }
bytes = { workspace = true }
futures-lite = { workspace = true }
headers = { workspace = true }
hickory-resolver = { workspace = true }
ipnet = { workspace = true }
opentelemetry = { workspace = true, optional = true }
opentelemetry-semantic-conventions = { workspace = true, optional = true }
opentelemetry_sdk = { workspace = true, optional = true }
parking_lot = { workspace = true }
paste = { workspace = true }
pin-project-lite = { workspace = true }
rama-core = { version = "0.2.0-alpha.2", path = "../rama-core" }
rama-http-types = { version = "0.2.0-alpha.2", path = "../rama-http-types", optional = true }
rama-utils = { version = "0.2.0-alpha.2", path = "../rama-utils" }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["macros", "fs", "io-std"] }
tokio-graceful = { workspace = true }
tracing = { workspace = true }
venndb = { workspace = true, optional = true }
boring = { workspace = true, optional = true }
rustls = { workspace = true, optional = true }
nom = { workspace = true, optional = true }
hex = { workspace = true, optional = true }

[dev-dependencies]
itertools = { workspace = true }
quickcheck = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-test = { workspace = true }

[package.metadata.cargo-public-api-crates]
allowed = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
