[package]
name = "rama-rt"
description = "async-first runtime for rama, a distortion proxy framework"
readme = "README.md"
version = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }
authors = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.33", features = ["net", "io-util", "rt-multi-thread"] }
tokio-graceful = "0.1"
tokio-rustls = "0.25.0-alpha.2"
tokio-test = "0.4.3"
