[package]
name = "rama-cli"
description = "binary version of and cli utility for rama, a modular service framework"
version = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }
authors = { workspace = true }
rust-version = { workspace = true }
default-run = "rama"

[dependencies]
argh = { workspace = true }
bytes = { workspace = true }
rama = { version = "0.2", path = ".." }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[[bin]]
name = "rama"
path = "src/main.rs"
