[package]
name = "rama-core"
description = "rama service core code, used by rama and service authors"
version = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }
authors = { workspace = true }
rust-version = { workspace = true }

[features]
default = []
full = ["telemetry", "venndb", "http"]
telemetry = [
    "dep:opentelemetry",
    "dep:opentelemetry_sdk",
    "dep:opentelemetry-semantic-conventions",
]
venndb = ["dep:venndb"]
http = ["dep:rama-http-types"]

[dependencies]
base64 = { workspace = true }
futures-lite = { workspace = true }
headers = { workspace = true }
hickory-resolver = { workspace = true }
opentelemetry = { workspace = true, optional = true }
opentelemetry-semantic-conventions = { workspace = true, optional = true }
opentelemetry_sdk = { workspace = true, optional = true }
parking_lot = { workspace = true }
paste = { workspace = true }
pin-project-lite = { workspace = true }
rama-error = { version = "0.2.0-alpha.2", path = "../rama-error" }
rama-http-types = { version = "0.2.0-alpha.2", path = "../rama-http-types", optional = true }
rama-macros = { version = "0.2.0-alpha.2", path = "../rama-macros" }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["macros", "fs", "io-std"] }
tokio-graceful = { workspace = true }
tracing = { workspace = true }
venndb = { workspace = true, optional = true }

[dev-dependencies]
quickcheck = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-test = { workspace = true }

[package.metadata.cargo-public-api-crates]
allowed = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
